# Generated by Django 4.1.7 on 2024-05-23 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubros',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('concepto', models.TextField(blank=True, null=True)),
                ('unidad', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicion_Pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatizacion_APUS.rubros')),
            ],
        ),
        migrations.CreateModel(
            name='Especificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatizacion_APUS.rubros')),
            ],
        ),
        migrations.CreateModel(
            name='Definicion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatizacion_APUS.rubros')),
            ],
        ),
    ]
