# Generated by Django 4.1.7 on 2024-05-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizacion_APUS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definicion',
            name='contenido',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='especificacion',
            name='contenido',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='medicion_pago',
            name='medicion',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='medicion_pago',
            name='metodoPago',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='rubros',
            name='categoria',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='rubros',
            name='concepto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rubros',
            name='especificaciones',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
