# Generated by Django 4.1.7 on 2024-05-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizacion_APUS', '0002_alter_definicion_contenido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubros',
            name='especificaciones',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
