# Generated by Django 4.1.7 on 2024-05-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizacion_APUS', '0003_alter_rubros_especificaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubros',
            name='rendimiento',
            field=models.FloatField(),
        ),
    ]
